Repository An-prog-hub/nodejs-user-auth, pull requests merged in 2022-10, with the labels that each got.

#2 Create main.js
  Auth0/main.js
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#3 [add]: _index.html + updated the styles w/ auth0 cdn
  Auth0/_index.html
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#4 [added] : evaluate-the-authentication-state
  Auth0/main.js
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#5 add: .gitignore file
  .gitignore
Labels: hacktoberfest-accepted

#6 Update server.js
  server.js
Labels: hacktoberfest-accepted, hacktoberfest
